### ISSUE TITLE
Return JSON with error details instead of HTML when validation fails

### ISSUE THREAD

**Issue by bartocc** [bug-hunters/oas3-tools#16]
I don't know if the upcoming 2.0.0 release will change this, but as for 1.0.1, a bad request correctly returns a 400 status, but with HTML content, with no details about what was wrong in the request.

It would be nice to have a JSON response instead, with details about the wrong request

**Comment by bartocc** [comment]
Ok, I'm gonna close this one. I guess I should implement a custom middleware to deal with the error from the validator and return whatever payload I want

**Comment by HugoMario** [comment]
hi @bartocc 

validations on this project are now handled by [express-openapi-validatdor](https://github.com/cdimascio/express-openapi-validator) dependency, which works with JSON response
