### ISSUE TITLE
Release 2.1.2 totally broken

### ISSUE THREAD

**Issue by Levino** [bug-hunters/oas3-tools#25]
Release 2.1.2 is totally broken. Check the [code](https://registry.npmjs.org/oas3-tools/-/oas3-tools-2.1.2.tgz). It looks like the person publishing this forgot to build before upload to npm. Only the TS files were uploaded, but none of the JS files in `dist/`. The package now is totally unusable because the `dist/index.js` is missing.

Also the version makes little sense to me. The last version before was `2.0.2` so the next "feature"-version should be `2.1.0` not `2.1.2`.

The `build` step should be added as a `prepublish` or `prepublishOnly` step. Also the TS files should not be uploaded anymore and therefore removed from the `files` entry in the `package.json`.
https://github.com/bug-hunters/oas3-tools/blob/03b58480f431cfea60803aa5fbf310e5e1119602/package.json#L35

**Comment by HugoMario** [comment]
thanks @Levino for reporting this, you are right about versioning, but i guess we should keep it this way now to avoid more confuse

**Comment by vnaganathan-conga** [comment]
@Levino is correct. @HugoMario There is no dist/index.js even though the package.json refers to it. So our swagger API docs are broken. Please withdraw the 2.1.2 release or fix it asap and release the correct version.

**Comment by Levino** [comment]
As a workaround you can pin the version to `2.0.2` until a patch is released.

I agree that `2.1.2` should be unpublished immediately to reduce wasted dev time for others.

**Comment by vnaganathan-conga** [comment]
@Levino - yes we will pin it down. I cannot believe the unproductive hours I spent troubleshooting the various parts of my app (as i assumed an npm package would be the last suspect). 2.1.2 should be taken down asap.

**Comment by Levino** [comment]
Stuff like this happens. I am grateful for all the free and great software supplied by folks like the maintainers of this project here. But still now one needs to act quickly and unpublish to avoid further fallout. Release of `2.1.3` can then be done carefully and calmly.

**Comment by vnaganathan-conga** [comment]
Totally agree. I am thankful to the wonderful work the authors of this package have done! Looking for 2.1.3 soon

**Comment by nishantshah-me** [comment]
Getting an error - module could not found.

**Comment by thomasgainant** [comment]
Still getting a module not found error, even though the package is downgraded to 2.0.2

**Comment by Levino** [comment]
Show a repo with a failing test please.

**Comment by thomasgainant** [comment]
Forgot to remove the "^" in package.json. Typed "oas3-tools": "2.0.2" instead of "oas3-tools": "^2.0.2", in dependencies and the problem was solved

**Comment by HugoMario** [comment]
sorry guys for delay, i've just pushed 2.1.3 version with fix.

**Comment by Levino** [comment]
Sorry, forgot to close.
